#! /bin/bash
 
echo "===> updating repo in html/i386"
(cd html/i386 ; createrepo .)
echo ""

echo "===> updating repo in html/SRPMS"
(cd html/SRPMS ; createrepo .)
echo ""

echo "===> updating repo in html/x86_64"
(cd html/x86_64 ; createrepo .)
echo ""
